-- LaundryApp sample data
-- These records are used to test the database relationships.


-- =====================================================
-- BUILDINGS
-- IDs generated: 1 and 2
-- =====================================================

INSERT INTO buildings (name, address)
VALUES
    ('Park Avenue Apartments', '120 Park Avenue, New York, NY'),
    ('Riverside Residences', '850 Riverside Drive, New York, NY');


-- =====================================================
-- USERS
-- The password hashes below are placeholders for
-- database testing only. The backend team must replace
-- them with real hashes generated by its login system.
-- =====================================================

INSERT INTO users (
    building_id,
    name,
    email,
    password_hash,
    role
)
VALUES
    (
        1,
        'Maya Chen',
        'maya.manager@example.com',
        'sample_hash_replace_later',
        'manager'
    ),
    (
        1,
        'Pedro Vera',
        'pedro.tenant@example.com',
        'sample_hash_replace_later',
        'tenant'
    ),
    (
        2,
        'Daniel Smith',
        'daniel.manager@example.com',
        'sample_hash_replace_later',
        'manager'
    ),
    (
        2,
        'Sofia Rivera',
        'sofia.tenant@example.com',
        'sample_hash_replace_later',
        'tenant'
    );


-- =====================================================
-- MACHINES
-- IDs generated: 1 through 4
-- =====================================================

INSERT INTO machines (
    building_id,
    machine_number,
    machine_type,
    cost_per_cycle,
    duration_minutes,
    status
)
VALUES
    (1, 1, 'washer', 3.00, 35, 'active'),
    (1, 1, 'dryer', 3.00, 40, 'active'),
    (2, 1, 'washer', 4.00, 35, 'active'),
    (2, 1, 'dryer', 4.00, 40, 'maintenance');


-- =====================================================
-- SUBSCRIPTION PLANS
-- IDs generated: 1 and 2
-- =====================================================

INSERT INTO subscription_plans (
    plan_name,
    billing_period,
    subscription_price,
    max_machines,
    analytics_level
)
VALUES
    ('Basic', 'monthly', 49.99, 10, 'basic'),
    ('Premium', 'monthly', 99.99, 30, 'premium');


-- =====================================================
-- BUILDING SUBSCRIPTIONS
-- =====================================================

INSERT INTO building_subscriptions (
    building_id,
    plan_id,
    start_date,
    end_date,
    subscription_status
)
VALUES
    (1, 2, '2026-07-01', NULL, 'active'),
    (2, 1, '2026-07-01', NULL, 'active');


-- =====================================================
-- BOOKINGS
-- =====================================================

INSERT INTO bookings (
    user_id,
    machine_id,
    start_time,
    end_time,
    price_at_booking,
    booking_status
)
VALUES
    (
        2,
        1,
        '2026-07-15 17:00:00',
        '2026-07-15 17:35:00',
        3.00,
        'completed'
    ),
    (
        2,
        2,
        '2026-07-18 18:00:00',
        '2026-07-18 18:40:00',
        3.00,
        'confirmed'
    ),
    (
        4,
        3,
        '2026-07-16 16:00:00',
        '2026-07-16 16:35:00',
        4.00,
        'completed'
    );


-- =====================================================
-- BOOKING PAYMENTS
-- LaundryApp receives a 5% transaction fee.
-- =====================================================

INSERT INTO booking_payments (
    booking_id,
    gross_amount,
    transaction_fee_rate,
    transaction_fee,
    building_amount,
    payment_status
)
VALUES
    (1, 3.00, 5.00, 0.15, 2.85, 'paid'),
    (3, 4.00, 5.00, 0.20, 3.80, 'paid');


-- =====================================================
-- SUBSCRIPTION PAYMENTS
-- These are direct SaaS revenues for LaundryApp.
-- =====================================================

INSERT INTO subscription_payments (
    subscription_id,
    amount,
    payment_status,
    billing_period_start,
    billing_period_end
)
VALUES
    (
        1,
        99.99,
        'paid',
        '2026-07-01',
        '2026-07-31'
    ),
    (
        2,
        49.99,
        'paid',
        '2026-07-01',
        '2026-07-31'
    );